name: Update and publish LazyCat app
on:
  push:
    tags: ["v*"]
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  lazycat:
    uses: ca-x/lazycat-github-action/.github/workflows/lazycat.yml@v1
    with:
      operation: auto
      config: .github/lazycat-action.yml
      versioned-release-asset: true
    secrets:
      LAZYCAT_TOKEN: ${{ secrets.LAZYCAT_TOKEN }}
      LZC_CLI_TOKEN: ${{ secrets.LZC_CLI_TOKEN }}
      APPSTORE_URL: ${{ secrets.APPSTORE_URL }}
      APPSTORE_TOKEN: ${{ secrets.APPSTORE_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_STORE_GROUP_CODES: ${{ secrets.PRIVATE_STORE_GROUP_CODES }}
